// Generated by CoffeeScript 1.6.2
/***
 @description 基于 jQuery 的多功能无缝滚动插件
 @params auto: true                     # 是否自动滚动
         interval: 3000                 # 间隔时间（毫秒）
         direction: 'forward'           # 向前 -  forward / 向后 - backward
         speed: 500                     # 移动速度（毫秒）
         showNum: 1                     # 显示个数
         stepLen: 1                     # 每次滚动步长
         type: 'horizontal'             # 水平滚动 - horizontal / 垂直滚动 - vertical
         prevElement: null              # 上一页按钮元素
         prevBefore: function() {}      # 上一页移动前回调
         prevAfter: function() {}       # 上一页移动后回调
         nextElement: null              # 下一页按钮元素
         nextBefore: function() {}      # 下一页移动前回调
         nextAfter: function() {}       # 下一页移动后回调
         pauseElement: null             # 暂停按钮元素
         pauseBefore: function() {}     # 暂停前回调
         pauseAfter: function() {}      # 暂停后回调
         resumeElement: null            # 继续按钮元素
         resumeBefore: function() {}    # 继续前回调
         resumeAfter: function() {}     # 继续后回调
 @author i@wange.im
 @url https://github.com/wange1228/marquee-slide
 @version 0.4.1
*/

(function($) {
  var Marquee;
  Marquee = (function() {
    function Marquee(element, options) {
      this.elements = {
        wrap: element,
        ul: element.children(),
        li: element.children().children()
      };
      this.settings = $.extend({}, $.fn.marquee.defaults, options);
      this.cache = {
        allowMarquee: true
      };
      return;
    }

    Marquee.prototype.init = function() {
      this.setStyle();
      this.move();
      this.bind();
    };

    Marquee.prototype.setStyle = function() {
      var floatStyle, liMargin, liOuterH, liOuterW, ulH, ulW, wrapH, wrapW;
      liOuterW = this.elements.li.outerWidth(true);
      liOuterH = this.elements.li.outerHeight(true);
      liMargin = Math.max(parseInt(this.elements.li.css('margin-top'), 10), parseInt(this.elements.li.css('margin-bottom'), 10));
      switch (this.settings.type) {
        case 'horizontal':
          wrapW = this.settings.showNum * liOuterW;
          wrapH = liOuterH;
          ulW = 9999;
          ulH = 'auto';
          floatStyle = 'left';
          this.cache.stepW = this.settings.stepLen * liOuterW;
          this.cache.prevAnimateObj = {
            left: -this.cache.stepW
          };
          this.cache.nextAnimateObj = {
            left: 0
          };
          this.cache.leftOrTop = 'left';
          break;
        case 'vertical':
          wrapW = liOuterW;
          wrapH = this.settings.showNum * liOuterH - liMargin;
          ulW = 'auto';
          ulH = 9999;
          floatStyle = 'none';
          this.cache.stepW = this.settings.stepLen * liOuterH - liMargin;
          this.cache.prevAnimateObj = {
            top: -this.cache.stepW
          };
          this.cache.nextAnimateObj = {
            top: 0
          };
          this.cache.leftOrTop = 'top';
      }
      this.elements.wrap.css({
        position: 'static' ? 'relative' : this.elements.wrap.css('position'),
        width: wrapW,
        height: wrapH,
        overflow: 'hidden'
      });
      this.elements.ul.css({
        position: 'relative',
        width: ulW,
        height: ulH
      });
      this.elements.li.css({
        float: floatStyle
      });
    };

    Marquee.prototype.bind = function() {
      var _ref, _ref1, _ref2, _ref3, _ref4, _this;
      _this = this;
      if ((_ref = this.settings.prevElement) != null) {
        _ref.click(function(ev) {
          ev.preventDefault();
          _this.prev();
        });
      }
      if ((_ref1 = this.settings.nextElement) != null) {
        _ref1.click(function(ev) {
          ev.preventDefault();
          _this.next();
        });
      }
      if ((_ref2 = this.settings.pauseElement) != null) {
        _ref2.click(function(ev) {
          ev.preventDefault();
          _this.pause();
        });
      }
      if ((_ref3 = this.settings.resumeElement) != null) {
        _ref3.click(function(ev) {
          ev.preventDefault();
          _this.resume();
        });
      }
      if ((_ref4 = this.elements.wrap) != null) {
        _ref4.hover(function() {
          _this.pause();
        }, function() {
          _this.resume();
        });
      }
    };

    Marquee.prototype.move = function() {
      var interval, moveEvent, _this;
      _this = this;
      if (this.settings.auto) {
        switch (this.settings.direction) {
          case 'forward':
            moveEvent = _this.prev;
            break;
          case 'backward':
            moveEvent = _this.next;
        }
        interval = _this.settings.interval;
        setTimeout(function() {
          moveEvent.call(_this);
          setTimeout(arguments.callee, interval);
        }, interval);
      }
    };

    Marquee.prototype.prev = function() {
      var preEls, _this;
      _this = this;
      if (this.cache.allowMarquee) {
        if (this.settings.auto === false) {
          this.cache.allowMarquee = false;
        }
        this.settings.prevBefore.call(this);
        preEls = this.elements.ul.children().slice(0, this.settings.stepLen);
        preEls.clone().appendTo(this.elements.ul);
        this.elements.ul.animate(this.cache.prevAnimateObj, this.settings.speed, function() {
          _this.elements.ul.css(_this.cache.leftOrTop, 0);
          preEls.remove();
          if (_this.settings.auto === false) {
            _this.cache.allowMarquee = true;
          }
          _this.settings.prevAfter.call(_this);
        });
      }
    };

    Marquee.prototype.next = function() {
      var sufEls, _this;
      _this = this;
      if (this.cache.allowMarquee) {
        if (this.settings.auto === false) {
          this.cache.allowMarquee = false;
        }
        this.settings.nextBefore.call(this);
        sufEls = this.elements.ul.children().slice(-this.settings.stepLen);
        sufEls.clone().prependTo(this.elements.ul);
        this.elements.ul.css(_this.cache.leftOrTop, -this.cache.stepW).animate(this.cache.nextAnimateObj, this.settings.speed, function() {
          sufEls.remove();
          if (_this.settings.auto === false) {
            _this.cache.allowMarquee = true;
          }
          _this.settings.nextAfter.call(_this);
        });
      }
    };

    Marquee.prototype.pause = function() {
      this.settings.pauseBefore.call(this);
      this.cache.allowMarquee = false;
      this.settings.pauseAfter.call(this);
    };

    Marquee.prototype.resume = function() {
      this.settings.resumeBefore.call(this);
      this.cache.allowMarquee = true;
      this.settings.resumeAfter.call(this);
    };

    return Marquee;

  })();
  $.fn.marquee = function(options) {
    this.each(function(key, value) {
      var marquee;
      marquee = new Marquee($(this), options);
      marquee.init();
    });
  };
  $.fn.marquee.defaults = {
    auto: true,
    interval: 3000,
    direction: 'forward',
    speed: 500,
    showNum: 1,
    stepLen: 1,
    type: 'horizontal',
    prevElement: null,
    prevBefore: function() {},
    prevAfter: function() {},
    nextElement: null,
    nextBefore: function() {},
    nextAfter: function() {},
    pauseElement: null,
    pauseBefore: function() {},
    pauseAfter: function() {},
    resumeElement: null,
    resumeBefore: function() {},
    resumeAfter: function() {}
  };
})(jQuery);
